markdown: kramdown
url: ''
baseurl: ''
title: Amala Suci
description: Pyramid Meditation 
site-image: /assets/images/meta.jpg
site-keywords: 'Crystal pyramids, pyramid meditation, prana pyramids, prana energy, epoxy pyramids, energy pyramids, coper pyramids'
favicon-url: /assets/images/meta.jpg
email: janis.juhnevics@gmail.com
facebook_username: janisJuh
twitter_username: janisJuh
instagram_username: janisJuh
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: UA-163806439-1
author-name: janisJuh
author-image: >-
  assets/images/pyramid/copper-pyramid.png
author-about: >-
  Amala Suci (अमला) crystals concentrate prana energy flow for dedicated meditation and communication between full spectrum of earth natural crystal resonant frequencies. Amala suci brass pyramid portals or prana flow amala crystal structures can be learnt and chosen by personal communication with Amala Swami. Arrange an appointment for further information. 
author-url: 'https://github.com/thedevslot'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
